//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalmonRiver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public int DateID { get; set; }
        public System.DateTime Date1 { get; set; }
        public Nullable<int> HolidayID { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Holiday Holiday { get; set; }
    }
}
