//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalmonRiver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hold
    {
        public int HoldID { get; set; }
        public int DateID { get; set; }
        public System.DateTime Expiration { get; set; }
    
        public virtual Date Date { get; set; }
    }
}
